<?php
if ( isset( $_GET[ 'k' ] ) ) {
	$k = preg_replace( "/[^[:alnum:]]/i", "", $_GET[ 'k' ] );
	if ( !isset( $_COOKIE[ $k ] ) || ( isset( $_COOKIE[ $k ] ) && $_COOKIE[ $k ] == 1 ) )
		@setcookie( $k, time(), time()+604800, '/' );
}

if ( isset( $_GET[ 'o' ] ) ) {
	header("Content-type: image/gif");
	readfile( './blank.gif' );
} else {
	header("Content-type: text/css");
	echo "/* Page generated by Cookies for Comments at http://ocaoimh.ie/cookies-for-comments/ */";
}
die();
?>
